### ISSUE TITLE
Rust Format

### ISSUE THREAD

**Issue by siedentop** [aquanauts/rizzy#5]
Thanks for this neat little utility!

Would it be possible for you to run Rust Format (`rustfmt`) on the code. This would make it more fun to contribute to your code.

If you prefer, you could enforce future compliance through the GitHub Actions.

[This example](https://github.com/actions-rs/meta/blob/master/recipes/matrix.md) suggests doing it this way:

```yaml
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
```
